var nama = 'yosua';
console.log(nama);

function sayBuah(){
    var buah = 'apel';
}

sayBuah();
// console.log(buah);

let name = 'yosuas';
console.log(name);

function saySayur(){
    var sayur = 'bayam';
}

// saySayur();
// console.log(sayur);

var minum = 'sprite';
console.log(minum);
minum = 'coca-cola';
console.log(minum);
var minum = 'teh';
console.log(minum);

let makan = 'ayam'
console.log(makan)
makan = 'ikan'
console.log(makan)

console.log(bangun)
var bangun = null
console.log(bangun)

// console.log(tidur)
// let tidur = 9
// console.log(tidur)

// const baca = 'buku';
// console.log(baca);
// baca = ''

const cobaFunction = function merek(){
    console.log('amd');
}

console.log(cobaFunction());

console.log(1.8E50);
console.log(BigInt(1e23));
console.log("it's yosua's apple");
console.log(1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000n);

console.log(typeof(NaN));

// console.log(Symbol('foo')  Symbol('foo'));

const foo = null ?? 'default string';
console.log(foo);
// expected output: "default string"
const baz = 0 ?? 42;
console.log(baz);
// expected output: 0


